name: pull_request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_windows_checks: false
      enable_macos_checks: false
      enable_linux_checks: true
      linux_os_versions: '["amazonlinux2", "bookworm", "jammy", "focal", "noble", "rhel-ubi9"]'
      linux_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}]"
      linux_pre_build_command: |
        if command -v apt-get >/dev/null 2>&1 ; then # bookworm, noble, jammy, focal
          /usr/sbin/sudo apt-get update -y
          /usr/sbin/sudo apt-get install -y default-jdk
        elif command -v yum >/dev/null 2>&1 ; then # amazonlinux2, rhel-ubi9
          /usr/sbin/sudo yum update -y
          /usr/sbin/sudo yum install -y openjdk
        fi

      enable_android_sdk_build: true
      enable_android_sdk_checks: true
  soundness:
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_enabled: false
      format_check_enabled: true
      license_header_check_project_name: Swift.org
      docs_check_enabled: false

  test-swift:
    name: Test (Swift) (${{ matrix.os_version }} swift:${{ matrix.swift_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: ['6.1.3', '6.2', 'nightly-6.3', 'nightly']
        os_version: ['jammy']
    container:
      image: ${{ (contains(matrix.swift_version, 'nightly') && 'swiftlang/swift') || 'swift' }}:${{ matrix.swift_version }}-${{ matrix.os_version }}
    steps:
      - uses: actions/checkout@v6
      - name: Prepare CI Environment
        uses: ./.github/actions/prepare_env
      - name: Swift Build
        run: swift build
      - name: Swift Test
        run: swift test
