name: pull_request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_enabled: false
      format_check_enabled: true
      license_header_check_project_name: Swift.org
      docs_check_enabled: false

  test-swift:
    name: Test (Swift) (${{ matrix.os_version }} swift:${{ matrix.swift_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: ['6.1.3', '6.2', 'nightly']
        os_version: ['jammy']
    container:
      image: ${{ (contains(matrix.swift_version, 'nightly') && 'swiftlang/swift') || 'swift' }}:${{ matrix.swift_version }}-${{ matrix.os_version }}
    steps:
      - uses: actions/checkout@v6
      - name: Prepare CI Environment
        uses: ./.github/actions/prepare_env
      - name: Swift Build
        run: swift build
      - name: Swift Test
        run: swift test

  construct-linkage-test-matrix:
    name: Construct linkage matrix
    runs-on: ubuntu-latest
    outputs:
      linkage-test-matrix: '${{ steps.generate-matrix.outputs.linkage-test-matrix }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - id: generate-matrix
        run: echo "linkage-test-matrix=$(curl -s https://raw.githubusercontent.com/apple/swift-nio/main/scripts/generate_matrix.sh | bash)" >> "$GITHUB_OUTPUT"
        env:
          MATRIX_LINUX_SETUP_COMMAND: apt-get update -y && apt-get install -yq jq && git config --global --add safe.directory /swift-java-jni-core
          MATRIX_LINUX_COMMAND: ./scripts/run-linkage-test.sh
          MATRIX_LINUX_5_10_ENABLED: false
          MATRIX_LINUX_6_0_ENABLED: false
          MATRIX_LINUX_6_1_ENABLED: false
          MATRIX_LINUX_NIGHTLY_NEXT_ENABLED: false
          MATRIX_LINUX_NIGHTLY_MAIN_ENABLED: false

  linkage-test:
    name: Linkage test
    needs: construct-linkage-test-matrix
    uses: apple/swift-nio/.github/workflows/swift_test_matrix.yml@main
    with:
      name: "Linkage test"
      matrix_string: '${{ needs.construct-linkage-test-matrix.outputs.linkage-test-matrix }}'
